name: Update gist with WakaTime stats
on:
  schedule:
    # Runs at 23:05am UTC+8
    - cron: '05 15 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # OS
          SHOW_OS: "False"
          # projects
          SHOW_PROJECTS: "False"
          # info
          SHOW_SHORT_INFO: "False"
          # show shape
          SYMBOL_VERSION: 1
          # debug message
          DEBUG_LOGGING: "False"
          # code lines
          SHOW_LINES_OF_CODE: "True"
          # repos
          SHOW_LANGUAGE_PER_REPO: "False"
          # chart
          SHOW_LOC_CHART: "False"
          # push name
          COMMIT_USERNAME: "HealUP"
          # EMAIL
          COMMIT_EMAIL: "denszhi@gmail.com"
